<?php
require_once '../../includes/config.php';
require_once '../../includes/autoload.php';

if (!isset($_SESSION['user'])) {
    header("Location: login.php");
    exit();
}

// Instantiate TwoFactorAuth.
$twoFA = new TwoFactorAuth();
$userId = $_SESSION['user']['id'];
$message = '';

// For simplicity, we assume that a user may enable 2FA by submitting a form with a verification code.
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['verification_code'])) {
    // Retrieve the temporary secret stored in the session.
    if (!isset($_SESSION['temp_totp_secret'])) {
        $message = "Your secret has expired. Please try again.";
    } else {
        $secret = $_SESSION['temp_totp_secret'];
        $verificationCode = trim($_POST['verification_code']);
        if ($twoFA->verifyCode($secret, $verificationCode)) {
            // Update user's record in the database.
            $db = Database::getInstance()->getConnection();
            $stmt = $db->prepare("UPDATE users SET totp_secret = ?, two_factor_enabled = 1 WHERE id = ?");
            if ($stmt->execute([$secret, $userId])) {
                $message = "2FA has been enabled successfully.";
                // Update session.
                $_SESSION['user']['two_factor_enabled'] = 1;
                $_SESSION['user']['totp_secret'] = $secret;
                // Remove temporary secret.
                unset($_SESSION['temp_totp_secret']);
            } else {
                $message = "Failed to update your settings. Please try again.";
            }
        } else {
            $message = "Verification code is incorrect. Please try again.";
        }
    }
}

// If 2FA is not yet enabled and there's no temporary secret, generate one.
if (!isset($_SESSION['temp_totp_secret'])) {
    $secret = $twoFA->generateSecret(); // Generate a new secret.
    $_SESSION['temp_totp_secret'] = $secret;
} else {
    $secret = $_SESSION['temp_totp_secret'];
}

$username = $_SESSION['user']['username'];
$issuer = "Finbelt Microfinance";
$otpauthUrl = $twoFA->getQRUrl($secret, $username, $issuer);
// Create a URL for a QR code using Google Chart API.
$qrCodeUrl = "https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl=" . urlencode($otpauthUrl) . "&choe=UTF-8";
?>
<?php include '../includes/header.php'; ?>
<main>
    <h2>Enable Two-Factor Authentication (2FA)</h2>
    <?php if ($message): ?>
        <p style="color:green;"><?php echo htmlspecialchars($message); ?></p>
    <?php endif; ?>
    <p>Scan the QR code below with your authenticator app (Google Authenticator, Authy, etc.).</p>
    <img src="<?php echo $qrCodeUrl; ?>" alt="2FA QR Code"><br><br>
    <p>If you cannot scan the QR code, manually enter this secret into your app: <strong><?php echo strtoupper($secret); ?></strong></p>
    <p>After setting up, enter the 6-digit code generated by your app below to verify and enable 2FA.</p>
    <form method="post" action="">
        <label for="verification_code">Verification Code:</label>
        <input type="text" name="verification_code" id="verification_code" maxlength="6" required>
        <button type="submit">Enable 2FA</button>
    </form>
</main>
<?php include '../includes/footer.php'; ?>
